# SPDX-License-Identifier: Apache-2.0
from .analysis_rules import (
    AnalysisRule,
    CommunicationHealthRule,
    CommunicationImbalanceRule,
    CrossLayerConsistencyRule,
    DataloaderStallRule,
    DistributedSkewRule,
    GpuUtilizationThroughputRule,
    LatencyBottleneckRule,
    LatencyOutlierRule,
    LatencyVarianceRule,
    MemoryGrowthRule,
    PipelineBubbleRule,
    RooflineGapRule,
)
from .distributed_alignment import align_stage_latency, analyze_rank_skew
from .evidence import (
    Claim,
    FusedAttribute,
    Provenance,
    attribute_kernel,
    claims_from_counters,
    claims_from_kernel_name,
    claims_from_launch_config,
    claims_from_nvtx,
    fuse_claims,
)
from .axes import (
    AXES,
    AXIS_IDS,
    Axis,
    axis_coverage,
    axis_for_category,
    axis_for_shipped_rule,
    summarize_axis_coverage,
)
from .measurement_context import (
    CacheState,
    MeasurementContext,
    compare_measurements,
    describe_collection_mode,
    measurement_collection_context,
)
from .metrics_analyzer import MetricsAnalyzer
from .nccl_bandwidth import (
    analyze_collective,
    arrivals_from_flight_recorder,
    detect_straggler,
    detect_straggler_from_traces,
)
from .trace_quality import (
    DATALOADER_ATTRIBUTION_SQL,
    QualityIssue,
    assess_trace_quality,
    check_autotuning,
    check_clock_alignment,
    check_cuda_graphs,
    check_dataloader_attribution,
    check_derived_metric_invariants,
    check_diagnostic_events,
    check_gpu_metric_gaps,
    check_kernel_name_uniqueness,
    check_multi_tenancy,
    check_nvlink_utilization_validity,
    check_profiler_overhead,
    check_rank_completeness,
    check_warmup,
    group_kernels_by_shape,
)
from .triage import TriageThresholds, TriageVerdict, triage_step
from .workload_profiles import (
    WORKLOAD_PROFILES,
    WorkloadProfile,
    build_rules_for_workload,
    list_workload_profiles,
    resolve_workload_profile,
)

__all__ = [
    "AnalysisRule",
    "LatencyBottleneckRule",
    "MemoryGrowthRule",
    "LatencyVarianceRule",
    "LatencyOutlierRule",
    "CommunicationImbalanceRule",
    "CommunicationHealthRule",
    "PipelineBubbleRule",
    "DataloaderStallRule",
    "GpuUtilizationThroughputRule",
    "DistributedSkewRule",
    "RooflineGapRule",
    "CrossLayerConsistencyRule",
    "align_stage_latency",
    "analyze_rank_skew",
    # Evidence fusion: conclusions carry where they came from.
    "Provenance",
    "Claim",
    "FusedAttribute",
    "fuse_claims",
    "attribute_kernel",
    "claims_from_kernel_name",
    "claims_from_launch_config",
    "claims_from_counters",
    "claims_from_nvtx",
    # Top-down triage.
    "triage_step",
    "TriageVerdict",
    "TriageThresholds",
    # Trace validity: refuse before analysing.
    "QualityIssue",
    "assess_trace_quality",
    "check_warmup",
    "check_autotuning",
    "check_cuda_graphs",
    "check_rank_completeness",
    "check_clock_alignment",
    "check_nvlink_utilization_validity",
    "check_diagnostic_events",
    "check_multi_tenancy",
    "check_dataloader_attribution",
    "DATALOADER_ATTRIBUTION_SQL",
    "check_kernel_name_uniqueness",
    "check_profiler_overhead",
    "check_gpu_metric_gaps",
    "check_derived_metric_invariants",
    "group_kernels_by_shape",
    # Collective bandwidth.
    "analyze_collective",
    "detect_straggler",
    "detect_straggler_from_traces",
    "arrivals_from_flight_recorder",
    # Performance axes: the shared vocabulary every finding maps onto.
    "Axis",
    "AXES",
    "AXIS_IDS",
    "axis_for_category",
    "axis_for_shipped_rule",
    "axis_coverage",
    "summarize_axis_coverage",
    # Measurement context: what a collection mode can and cannot answer.
    "CacheState",
    "MeasurementContext",
    "describe_collection_mode",
    "measurement_collection_context",
    "compare_measurements",
    "MetricsAnalyzer",
    "WORKLOAD_PROFILES",
    "WorkloadProfile",
    "resolve_workload_profile",
    "list_workload_profiles",
    "build_rules_for_workload",
]
